# Generated by Django 5.0.1 on 2024-01-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='user_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
